### ISSUE TITLE
Windows Inline script SCP error

### ISSUE THREAD

**Issue by WokiOz** [rundeck-plugins/sshj-plugin#17]
Hello, using this plugin to connect my windows servers throw ssh. Commands work well, but inline script had some issues.

Thanks,
ED

`net.schmizz.sshj.xfer.scp.SCPRemoteException: Remote SCP command had error: scp: '/tmp/9882-170589-MYHOST-dispatch-script.tmp.ps1': No such file or directory

 

at net.schmizz.sshj.xfer.scp.SCPEngine.check(SCPEngine.java:73)

 

at net.schmizz.sshj.xfer.scp.SCPEngine.sendMessage(SCPEngine.java:133)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.sendFile(SCPUploadClient.java:105)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.process(SCPUploadClient.java:84)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.startCopy(SCPUploadClient.java:76)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:54)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:47)

 

at net.schmizz.sshj.xfer.scp.SCPUploadClient.copy(SCPUploadClient.java:43)

 

at net.schmizz.sshj.xfer.scp.SCPFileTransfer.upload(SCPFileTransfer.java:98)

 

at net.schmizz.sshj.xfer.scp.SCPFileTransfer.upload(SCPFileTransfer.java:91)

 

at com.plugin.sshjplugin.model.SSHJScp.execute(SSHJScp.java:54)

 

at com.plugin.sshjplugin.SSHJFileCopierPlugin.copyFile(SSHJFileCopierPlugin.java:166)

 

at com.plugin.sshjplugin.SSHJFileCopierPlugin.copyFile(SSHJFileCopierPlugin.java:96)

 

at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.fileCopyFile(ExecutionServiceImpl.java:320)

 

at com.dtolabs.rundeck.core.execution.ExecutionService$fileCopyFile$5.call(Unknown Source)

 

at com.rundeck.runner.service.RunnerExecutionService.fileCopyFile(RunnerExecutionService.groovy:147)

 

at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.DefaultScriptFileNodeStepUtils.executeScriptFile(DefaultScriptFileNodeStepUtils.java:119)

 

at com.dtolabs.rundeck.core.execution.workflow.steps.node.impl.ScriptFileNodeStepExecutor.executeNodeStep(ScriptFileNodeStepExecutor.java:81)

 

at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:207)

 

at com.dtolabs.rundeck.core.execution.ExecutionService$executeNodeStep$2.call(Unknown Source)`

**Comment by w00dst0ck** [comment]
+1

Just had the same experience.
