### ISSUE TITLE
Inline script SCP error on Windows

### ISSUE THREAD

**Issue by RicCanuto** [rundeck-plugins/sshj-plugin#65]
Hi,
I have installed rundeck version 5.2.0 on a windows server and I'm trying to use the sshj-plugin to execute a Inline script on a remote windows server.
I'm getting a strange error:
`[sshj-scp] SSHJ File Copier
[sshj-scp] Copying file C:\Rundeck\var\tmp\dispatch17945963775992498244.tmp.bat to C:\Users\ricardo.canuto\45-108-pt-srvdb1lx1-dispatch-script.tmp.bat
[net.schmizz.concurrent.Promise] Awaiting <<chan#0 / open>>
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Initialized - < session channel: id=0, recipient=0, localWin=[winSize=2097152], remoteWin=[winSize=0] >
[net.schmizz.concurrent.Promise] Setting <<chan#0 / open>> to `SOME`
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Will request to exec `scp -t -r -p 'C:\Users\ricardo.canuto\45-108-pt-srvdb1lx1-dispatch-script.tmp.bat'`
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Sending channel request for `exec`
[net.schmizz.concurrent.Promise] Awaiting <<chan#0 / chanreq for exec>>
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Received window adjustment for 2097152 bytes
[net.schmizz.sshj.connection.channel.Window$Remote] Increasing by 2097152 up to 2097152
[net.schmizz.concurrent.Promise] Setting <<chan#0 / chanreq for exec>> to `SOME`
[net.schmizz.sshj.connection.channel.Window$Local] Consuming by 1 down to 2097151
[net.schmizz.sshj.connection.channel.Window$Remote] Consuming by 27 down to 2097125
[net.schmizz.sshj.connection.channel.Window$Local] Consuming by 1 down to 2097150
[net.schmizz.sshj.connection.channel.Window$Remote] Consuming by 47 down to 2097078
[net.schmizz.sshj.connection.channel.Window$Local] Consuming by 103 down to 2097047
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Sending close
[net.schmizz.concurrent.Promise] Awaiting <<chan#0 / close>>
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Got chan request for `exit-status`
[net.schmizz.sshj.connection.channel.direct.SessionChannel] Got close
[net.schmizz.concurrent.Promise] Setting <<chan#0 / close>> to `SOME`
net.schmizz.sshj.xfer.scp.SCPRemoteException: Remote SCP command had error: scp: 'C:/Users/ricardo.canuto/45-108-pt-srvdb1lx1-dispatch-script.tmp.bat': No such file or directory
	at net.schmizz.sshj.xfer.scp.SCPEngine.check(SCPEngine.java:73)
	at net.schmizz.sshj.xfer.scp.SCPEngine.sendMessage(SCPEngine.java:133)
	at net.schmizz.sshj.xfer.scp.SCPUploadClient.sendFile(SCPUploadClient.java:105)` 

When executing the rundeck job, I have checked the dir C:\Rundeck\var\tmp\ and I saw, temporally, the file dispatch17945963775992498244.tmp.bat.

Note: I have defined the folowwing properties on the node:
file-copy-destination-dir: 'C:\Users\ricardo.canuto'
osFamily: windows

Can anyone help me please? I'm facing this error a while ago.

Thank you

**Comment by fdevans** [comment]
Sorry we missed this.  We've made significant updates to the plugin since you posted.   If you encounter this again please open a new issue.
